### ISSUE TITLE
Debian: compilation error as of 5b0eadd

### ISSUE THREAD

**Issue by SecDorks-Kirc** [CESNET/ipfixcol#33]
The IPFIXcol `base` package does not compile anymore on Debian (v7.8) systems as of 5b0eadd4e93c3be5288f906b7e827d1126b357fb:

```
configurator.c: In function 'config_compare_xml':
configurator.c:574:2: error: unknown type name 'xmlBufPtr'
configurator.c:574:19: warning: initialization makes integer from pointer without a cast [enabled by default]
configurator.c:576:2: warning: implicit declaration of function 'xmlBufGetNodeContent' [-Wimplicit-function-declaration]
configurator.c:577:2: warning: implicit declaration of function 'xmlBufContent' [-Wimplicit-function-declaration]
configurator.c:577:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
configurator.c:580:2: error: unknown type name 'xmlBufPtr'
configurator.c:580:19: warning: initialization makes integer from pointer without a cast [enabled by default]
configurator.c:583:25: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
configurator.c:598:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
configurator.c:599:16: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
```
So far, I've not been able to discover what in 5b0eadd4e93c3be5288f906b7e827d1126b357fb is actually causing this behavior. It works fine on Ubuntu (v14.04.1) Do you have any clue?

**Comment by evertlammerts** [comment]
Same problem here, on RHEL 6.6 (libxml2 and libxml2-devel 2.7.6-17 are installed)

**Comment by mikeek** [comment]
This is propably a problem with libxml2 library. In version <= 2.8.x there is `xmlBuffer` structure, but in 2.9.0, it is replaced by the new one, `xmlBuf` and `xmlBuffer` is marked as deprecated. I'll try to find a solution to keep compatibility with the older versions.

**Comment by evertlammerts** [comment]
Something like this? https://gist.github.com/evertlammerts/1a50f37ff8cc2c4c84ef

Seems to compile now...

**Comment by mikeek** [comment]
Fixed in d096ec79dea5d32b53eca42eb9a448c4fc8decb9
