### ISSUE TITLE
cannot compile lnfstore

### ISSUE THREAD

**Issue by bodik** [CESNET/ipfixcol#155]
hello, please note the tail of compile log down below. ipfixcol plugin lnfstore cannot be compiled anymore. last working version comes from Dec15 (b4599aa)
------------------------------------
  ipfixcol-lnfstore-output version 0.2.5
  Prefix........: /usr/local
  Distribution..: debian
  C Compiler....: gcc -Wall -std=gnu99 -I/usr/include/libxml2  -I./../../../base/headers
  Linker........:  -lnf -lxml2 
  rpmbuild......: rpmbuild
  Build doc.....: yes
  xsltproc......: xsltproc
  xsltmanstyle..: /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl

make  all-am
make[1]: Entering directory '/tmp/build_area/ipfixcol/plugins/storage/lnfstore'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.   -I/usr/include/libxml2  -I./../../../base/headers  -Wall -std=gnu99 -MT lnfstore.lo -MD -MP -MF .deps/lnfstore.Tpo -c -o lnfstore.lo lnfstore.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/libxml2 -I./../../../base/headers -Wall -std=gnu99 -MT lnfstore.lo -MD -MP -MF .deps/lnfstore.Tpo -c lnfstore.c  -fPIC -DPIC -o .libs/lnfstore.o
mv -f .deps/lnfstore.Tpo .deps/lnfstore.Plo
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.   -I/usr/include/libxml2  -I./../../../base/headers  -Wall -std=gnu99 -MT storage.lo -MD -MP -MF .deps/storage.Tpo -c -o storage.lo storage.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/libxml2 -I./../../../base/headers -Wall -std=gnu99 -MT storage.lo -MD -MP -MF .deps/storage.Tpo -c storage.c  -fPIC -DPIC -o .libs/storage.o
mv -f .deps/storage.Tpo .deps/storage.Plo
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.   -I/usr/include/libxml2  -I./../../../base/headers  -Wall -std=gnu99 -MT translator.lo -MD -MP -MF .deps/translator.Tpo -c -o translator.lo translator.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I/usr/include/libxml2 -I./../../../base/headers -Wall -std=gnu99 -MT translator.lo -MD -MP -MF .deps/translator.Tpo -c translator.c  -fPIC -DPIC -o .libs/translator.o
translator.c: In function 'tr_general':
translator.c:186:38: error: 'LNF_FLD_INFO_SIZE' undeclared (first use in this function)
  if (lnf_fld_info(item_info->lnf_id, LNF_FLD_INFO_SIZE, &size,
                                      ^
translator.c:186:38: note: each undeclared identifier is reported only once for each function it appears in
Makefile:491: recipe for target 'translator.lo' failed
make[1]: *** [translator.lo] Error 1
make[1]: Leaving directory '/tmp/build_area/ipfixcol/plugins/storage/lnfstore'
Makefile:371: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by thorgrin** [comment]
Hi, I cannot reproduce this issue, so I'll need a bit more information. What version of libnf do you use? I have it working with libnf-1.17.

**Comment by bodik** [comment]
thank you for advice, i'm using 1.16. i'll try with a newer version and will let you know

**Comment by bodik** [comment]
libnf 1.17 work like a charm. thank you for help.
